=== adehad/dhikr-hub/qasida.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://example.com/example.json",
    "title": "Root Schema",
    "type": "object",
    "default": {},
    "required": [
        "name",
        "verses",
        "translation",
        "order"
    ],
    "properties": {
        "name": {
            "title": "The name Schema",
            "type": "object",
            "default": {},
            "required": [
                "ara",
                "en"
            ],
            "properties": {
                "ara": {
                    "title": "The ara Schema",
                    "type": "array",
                    "default": [],
                    "items": {},
                    "examples": [
                        []
                    ]
                },
                "en": {
                    "title": "The en Schema",
                    "type": "array",
                    "default": [],
                    "items": {},
                    "examples": [
                        []
                    ]
                }
            },
            "examples": [
                {
                    "ara": [],
                    "en": []
                }
            ]
        },
        "verses": {
            "title": "The verses Schema",
            "type": "object",
            "default": {},
            "required": [
                "ara",
                "en"
            ],
            "properties": {
                "ara": {
                    "title": "The ara Schema",
                    "type": "array",
                    "default": [],
                    "items": {
                        "title": "A Schema",
                        "type": "array",
                        "default": [],
                        "items": {
                            "title": "A Schema",
                            "type": "string",
                            "examples": [
                                "ﻃَﺎﻟَﻤَﺎ",
                                "ﺍَﺷْﻜُﻮْ",
                                "ﻏَﺮَﺍﻣِﻰ"
                            ]
                        },
                        "examples": [
                            [
                                "ﻃَﺎﻟَﻤَﺎ",
                                "ﺍَﺷْﻜُﻮْ",
                                "ﻏَﺮَﺍﻣِﻰ"
                            ]
                        ]
                    },
                    "examples": [
                        [
                            [
                                "ﻃَﺎﻟَﻤَﺎ",
                                "ﺍَﺷْﻜُﻮْ",
                                "ﻏَﺮَﺍﻣِﻰ"
                            ]
                        ]
                    ]
                },
                "en": {
                    "title": "The en Schema",
                    "type": "array",
                    "default": [],
                    "items": {
                        "title": "A Schema",
                        "type": "array",
                        "default": [],
                        "items": {
                            "title": "A Schema",
                            "type": "string",
                            "examples": [
                                "Tholama",
                                "ashku",
                                "gharami"
                            ]
                        },
                        "examples": [
                            [
                                "Tholama",
                                "ashku",
                                "gharami"
                            ]
                        ]
                    },
                    "examples": [
                        [
                            [
                                "Tholama",
                                "ashku",
                                "gharami"
                            ]
                        ]
                    ]
                }
            },
            "examples": [
                {
                    "ara": [
                        [
                            "ﻃَﺎﻟَﻤَﺎ",
                            "ﺍَﺷْﻜُﻮْ",
                            "ﻏَﺮَﺍﻣِﻰ"
                        ]
                    ],
                    "en": [
                        [
                            "Tholama",
                            "ashku",
                            "gharami"
                        ]
                    ]
                }
            ]
        },
        "translation": {
            "title": "The translation Schema",
            "type": "object",
            "default": {},
            "required": [
                "en"
            ],
            "properties": {
                "en": {
                    "title": "The en Schema",
                    "type": "array",
                    "default": [],
                    "items": {
                        "title": "A Schema",
                        "type": "array",
                        "default": [],
                        "items": {
                            "title": "A Schema",
                            "type": "string",
                            "examples": [
                                "How long",
                                "will I yearn, infaturated",
                                ""
                            ]
                        },
                        "examples": [
                            [
                                "How long",
                                "will I yearn, infaturated",
                                ""
                            ]
                        ]
                    },
                    "examples": [
                        [
                            [
                                "How long",
                                "will I yearn, infaturated",
                                ""
                            ]
                        ]
                    ]
                }
            },
            "examples": [
                {
                    "en": [
                        [
                            "How long",
                            "will I yearn, infaturated",
                            ""
                        ]
                    ]
                }
            ]
        },
        "order": {
            "title": "The order Schema",
            "type": "array",
            "default": [],
            "items": {
                "title": "A Schema",
                "type": "integer",
                "examples": [
                    0,
                    1
                ]
            },
            "examples": [
                [
                    0,
                    1
                ]
            ]
        }
    },
    "examples": [
        {
            "name": {
                "ara": [],
                "en": []
            },
            "verses": {
                "ara": [
                    [
                        "ﻃَﺎﻟَﻤَﺎ",
                        "ﺍَﺷْﻜُﻮْ",
                        "ﻏَﺮَﺍﻣِﻰ"
                    ]
                ],
                "en": [
                    [
                        "Tholama",
                        "ashku",
                        "gharami"
                    ]
                ]
            },
            "translation": {
                "en": [
                    [
                        "How long",
                        "will I yearn, infaturated",
                        ""
                    ]
                ]
            },
            "order": [
                0,
                1
            ]
        }
    ]
}

=== adehad/dhikr-hub/example.json
{
    "name": {
        "ara": [],
        "en": []
    },
    "verses": {
        "ara": [
            [
                "ﻃَﺎﻟَﻤَﺎ",
                "ﺍَﺷْﻜُﻮْ",
                "ﻏَﺮَﺍﻣِﻰ"
            ]
        ],
        "en": [
            [
                "Tholama",
                "ashku",
                "gharami"
            ]
        ]
    },
    "translation": {
        "en": [
            [
                "How long",
                "will I yearn, infaturated",
                ""
            ]
        ]
    },
    "order": [
        0,
        1
    ]
}
